# Methow Valley local data archive: Setup

# NOTE:  https://mazamascience.github.io/MazamaCoreUtils/articles/logging.html

```{r}
library(MazamaCoreUtils)    # for logging
library(AirSensor)
```

```{r}
# ----- Setup ------------------------------------------------------------------

# Use the default archiveDir unless it is already defined
if ( !exists("archiveDir") ) {
  archiveDir <- file.path("~/Data/MVCAA")
}

dir.create(archiveDir, recursive = TRUE)

# AirSensor package
library(AirSensor)

# Set the archiveBaseUrl so we can get a pre-generated 'pas' object
setArchiveBaseUrl("http://data.mazamascience.com/PurpleAir/v1")

# ----- Subset PAS object ------------------------------------------------------

# Create a 'pas' object limited to MVCAA sensors
#   - load most recent 'pas' for the entire country
#   - subset to include sensors labeled MVCAA
mvcaa <-
  pas_load() %>%
  filter(countryCode == "US") %>%
  filter(stateCode == "CA") 
  #filter(latitude >= 33.61 & latitude <= 33.87) %>%
  #filter(longitude >= -118.31 & longitude <= -118.09)

# Save it in our archive directory
save(mvcaa, file = file.path(archiveDir, "mvcaa.rda"))

# Examine archive directory:
list.files(file.path(archiveDir))
```

```{r}
# ----- Get PAS object ---------------------------------------------------------

# NOTE:  We won't use the archive directories for the pas object because we
# NOTE:  already have exactly what we want in our `mvcaa.rda` file.

mvcaa <- get(load(file.path(archiveDir, "mvcaa.rda")))
```


```{r}
# ----- Prepare PAT info -------------------------------------------------------

# Get all the deviceDeploymentIDs
mvcaa_ids <- pas_getDeviceDeploymentIDs(mvcaa)

# Set up months
timezone <- "America/Los_Angeles"
monthStamps <- c(202111)

# Loop over months
for ( monthStamp in monthStamps ) {

  logger.debug("Working on monthStamp %s ---------- ...", monthStamp) 
  
  # Get POSXct startdate
  startdate <- MazamaCoreUtils::parseDatetime(monthStamp, timezone = timezone)
  
  # Guarantee that the enddate is the first of the next month
  enddate <- lubridate::floor_date(
    startdate + lubridate::ddays(40),
    unit = "month"
  )
  
  # Get YYYY and MM strings
  YYYY <- strftime(startdate, "%Y")
  MM <- strftime(startdate, "%m")
  
  # Initialize counters
  idCount <- length(mvcaa_ids)
  count <- 0 
  successCount <- 0
}
```
  
```{r}
# ----- Create PAT objects ---------------------------------------------------

  # Create the archiveDir/pat/YYYY/MM/ directory
  dir.create(
    file.path(archiveDir, "pat", YYYY, MM), 
    showWarnings = FALSE,
    recursive = TRUE
  )
  
  # Loop over all deviceDeploymentIDs
  for ( id in mvcaa_ids ) {

    # Create PAT canonical file name
    fileName <- paste0("pat_", id, "_", YYYY, MM, ".rda")

    # Create PAT canonical file path
    filePath <- file.path(archiveDir, "pat", YYYY, MM, fileName)

    count <- count + 1
    logger.debug("Working on %s (%d/%d) ...", id, count, idCount)

    # Use a try-block in case you get "no data" errors
    result <- try({

      # Create PAT
      pat <- pat_createNew(
        id = id,
        label = NULL,        # not needed if you have the id
        pas = mvcaa,
        startdate = startdate,
        enddate = enddate,
        timezone = timezone,
        baseUrl = "https://api.thingspeak.com/channels/",
        verbose = FALSE
      )
      successCount <- successCount + 1
      save(pat, file = filePath)

    }, silent = FALSE)

    if ( "try-error" %in% class(result) ) {
      logger.error(geterrmessage())
    }

  }
```  
  
```{r}  
  # ------ Create AirSensor objects --------------------------------------------
  
  # Create the archiveDir/airsensor/YYYY/ directory
  dir.create(
    file.path(archiveDir, "airsensor", YYYY), 
    showWarnings = FALSE,
    recursive = TRUE
  )
  
  # Assign a collection name that makes sense
  collectionName <- "mvcaa"
  
  # Init counts
  successCount <- 0
  count <- 0
  
  dataList <- list()
  
  # Loop over all ids and aggregate to hourly
  for ( id in mvcaa_ids ) {
    
    count <- count + 1
    
    # Debug info
    logger.debug(
      "%4d/%d Calling pat_createAirSensor('%s')",
      count,
      length(mvcaa_ids),
      id
    )
    
    # Load the pat data, convert to an airsensor and add to dataList
    dataList[[id]] <- tryCatch(
      expr = {
        airsensor <- pat_load(
          id = id,
          label = NULL,
          pas = mvcaa,
          startdate = startdate,
          enddate = enddate,
          timezone = "America/Los_Angeles"
        ) %>%
          pat_createAirSensor(
            FUN = AirSensor::PurpleAirQC_hourly_AB_03
          )
      }, 
      error = function(e) {
        logger.warn('Unable to load PAT data for %s ', id)
        NULL
      }
      
      # Keep going in the face of errors
    )
    
    
  } # END of deviceDeploymentIDs loop
  
  # Combine the airsensors into a single airsensor object and save
  tryCatch(
    expr = {
      logger.info('Combining airsensors...')
      
      airsensor <- PWFSLSmoke::monitor_combine(dataList)
      class(airsensor) <- c("airsensor", "ws_monitor", "list")
      
      logger.info('Combined successfully...')
      
      # Create Airsensor canonical file name
      fileName <- paste0("airsensor_", collectionName, "_", YYYY, MM, ".rda")
      
      # Create Airsensor canonical file path
      filePath <- file.path(archiveDir, "airsensor", YYYY, fileName)

      save(list = "airsensor", file = filePath)
    }, 
    error = function(e) {
      msg <- paste("Error creating monthly AirSensor file: ", e)
      logger.error(msg)
    }
  )

  # Now proceed to the next month

```