

```{r}
# ----- Create PAT objects -----------------------------------------------------
mvcaa <- get(load(file.path(archiveDir, "mvcaa.rda")))

# Get all the deviceDeploymentIDs
mvcaa_ids <- pas_getDeviceDeploymentIDs(mvcaa)

# Specify time range
startdate <- "2021-12-01"
enddate <- "2022-01-01"
timezone <- "America/Los_Angeles"

# Create an empty List to store things
patList <- list()

# Initialize counters
idCount <- length(mvcaa_ids)
count <- 0 
successCount <- 0
month <- "patList12.rda"
```

```{r}
# Loop over all ids and get data (This might take a while.)
for (id in mvcaa_ids[1:idCount]) {
  
  count <- count + 1
  print(sprintf("Working on %s (%d/%d) ...", id, count, idCount))
  
  # Use a try-block in case you get "no data" errors
  result <- try({
    
    # Here we show the full function signature so you can see all possible arguments
    patList[[id]] <- pat_createNew(
      id = id,
      label = NULL,        # not needed if you have the id
      pas = mvcaa,
      startdate = startdate,
      enddate = enddate,
      timezone = timezone,
      baseUrl = "https://api.thingspeak.com/channels/",
      verbose = FALSE
    )
    successCount <- successCount + 1
    
  }, silent = FALSE)
  
  if ( "try-error" %in% class(result) ) {
    print(geterrmessage())
  }
  
}
```

```{r}
# How many did we get?
print(sprintf("Successfully created %d/%d pat objects.", successCount, idCount))

# Save it in our archive directory
save(patList, file = file.path(archiveDir, month))

# ----- Evaluate patList -------------------------------------------------------

# We can use sapply() to apply a function to each element of the list
sapply(patList, function(x) { return(x$meta$label) })

# How big is patList in memory?
print(object.size(patList), units = "MB")

# How big patList.rda on disk (as compressed binary) 
fileSize <- file.size(file.path(archiveDir, month))
sprintf("%.1f Mb", fileSize/1e6)
```

```{r}
# ----- Setup ------------------------------------------------------------------

# Have log messages sent to the console
MazamaCoreUtils::logger.setLevel(TRACE)

# Use the default archiveDir unless it is already defined
if ( !exists("archiveDir") ) {
  archiveDir <- file.path("~/Data/MVCAA")
}

# Set the package archiveBaseDir so we can load pat objects with `pat_load()`
setArchiveBaseDir(archiveDir)
```

```{r}
# Load previously generated 'pas' and 'pat' data
mvcaa <- get(load(file.path(archiveDir, "mvcaa.rda")))
patList <- get(load(file.path(archiveDir, month)))

# ----- Create 'airsensor' data ------------------------------------------------

# Create an empty List to store things
airsensorList <- list()
airsensorList2 <- list()
airsensorList3 <- list()

# Initialize counters
idCount <- length(patList)
count <- 0
successCount <- 0
```

```{r}
# Loop over ids and create 'airsensor' objects (might take a while).
for ( id in names(patList) ) {

  count <- count + 1
  print(sprintf("Working on %s (%d/%d) ...", id, count, idCount))
  
  # Use a try-block in case you get "no data" errors
  result <- try({
    
    # It's nice to copy-paste the full function signature so you can see all possible arguments
    airsensorList[[id]] <- pat_createAirSensor(
      pat = patList[[id]],
      parameter <- "pm25",
      FUN = PurpleAirQC_hourly_AB_01
    )
    
    airsensorList2[[id]] <- pat_createAirSensor(
      pat = patList[[id]],
      parameter <- "pm25",
      FUN = PurpleAirQC_hourly_AB_02
    )
    
    airsensorList3[[id]] <- pat_createAirSensor(
      pat = patList[[id]],
      parameter <- "pm25",
      FUN = PurpleAirQC_hourly_AB_03
    )
    successCount <- successCount + 1
    
  1}, silent = FALSE)

  if ( "try-error" %in% class(result) ) {
    print(geterrmessage())
  }
  
}



# How many did we get?
print(sprintf("Successfully created %d/%d pat objects.", successCount, idCount))

# Save it in our archive directory
save(airsensorList, file = file.path(archiveDir, "airsensorList_PM12_01.rda"))
save(airsensorList2, file = file.path(archiveDir, "airsensorList_PM12_02.rda"))
save(airsensorList3, file = file.path(archiveDir, "airsensorList_PM12_03.rda"))
```